AllCops:
  Exclude:
    - smaug.rb
    - smaug/**/*

Style/Documentation:
  Enabled: false
Style/GlobalVars:
  Enabled: false
Style/RedundantFileExtensionInRequire:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*
Metrics/MethodLength:
  Max: 15
Metrics/ParameterLists:
  Enabled: false
