[package]
name = "dr-input-manager"
authors = ["iMacTia"]
version = "0.1.0"
homepage = "https://github.com/iMacTia/dr-input-manager"
keywords = ['dragonruby', 'input']

# Optional:
# documentation = "https://example.com"
repository = "https://github.com/iMacTia/dr-input-manager"

# Which files do you want to be automatically required from your package.
requires = ["lib/input_manager.rb"]


[package.installs]
# Example
#
# <from> = <to>
# "lib/library.rb" = "app/lib/library.rb"

[dragonruby]
version = "5.5"
edition = "standard"
